# Generated by Django 5.1.1 on 2024-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Bio', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
