# Generated by Django 5.1.1 on 2024-09-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_rename_bio_profile_bio_alter_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
    ]
