# Generated by Django 5.1.1 on 2024-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0006_rename_name_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_list', to='Members.profile'),
        ),
    ]
